### ISSUE TITLE
Error after 'companion-update' to latest beta

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion-module-raspberry-gpio#19]
After updating companion, the gpio module crashes. All debian packages are up to date via `apt upgrade`.

```
system: ** Starting Connection from "/opt/companion/bundled-modules/raspberry-gpio/main.js" **
system: ** Connection started **
error: node:internal/modules/cjs/loader:1460
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/companion/bundled-modules/raspberry-gpio/prebuilds/julusian-epoll-linux-arm64/node-napi-v8.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at I (/opt/companion/bundled-modules/raspberry-gpio/main.js:1:415659)
    at /opt/companion/bundled-modules/raspberry-gpio/main.js:1:399013
    at 7107 (/opt/companion/bundled-modules/raspberry-gpio/main.js:1:399133)
    at n (/opt/companion/bundled-modules/raspberry-gpio/main.js:1:489818)
    at 8419 (/opt/companion/bundled-modules/raspberry-gpio/main.js:1:405297) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.20.2
system: ** Connection stopped **
```

**Comment by Julusian** [comment]
What version of debian is it? `cat /etc/debian_version` will give the version number

**Comment by istnv** [comment]
Debian 11.9
It was a companion pi image a couple of years ago that has been periodically updated.

**Comment by Julusian** [comment]
hopefully v1.2.1 of this module will fix it, once it bubbles through to the builds

**Comment by istnv** [comment]
Works fine, now. Thanks.
